apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
  namespace: default
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    service: db
  type: ClusterIP