apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  name: redis
  namespace: default
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: redis
  type: ClusterIP
